##:kivy!

<UserScreen>:
    user_title: user_title
    user_id: user_id

    FloatLayout:
        MDTopAppBar:
            id: user_title
            md_bg_color: 0.5, 0, 0.5, 1
            pos_hint: {'top': 1}
            title: 'User'
            left_action_items:
                [["arrow-left", lambda x: app.change_screen('menu')]]
        MDLabel:
            id: user_id
            text: 'User'