##:kivy!

<MainScreenManager>:
    MenuScreen:
        id: mn
        name: 'menu_screen'
    ScannerScreen:
        id: sc 
        name: 'scanner_screen'
    ProductScreen:
        id: prd
        name: 'product_screen'
    StockScreen:
        id: stck
        name: 'stock_screen'
    SignInScreen:
        id: sgn
        name: 'signin_screen'
    LoginScreen:
        id: lgn
        name: 'login_screen'
    UserScreen:
        id: usr
        name: 'user_screen'